version: "3"

services:

  client:
    image: nginx
    container_name: nginx-web
    hostname: nginx-web
    ports:
        - 8000:80
    volumes:
        - ./src:/usr/share/nginx/html
          
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 10s
